[package]
name = "miru_renderer"
version = "0.1.4"
edition = "2021"
license-file = "LICENSE"
[[bin]]
name = "miru"
path = "src/main.rs"
[lib]
name = "miru_renderer"
path = "src/lib.rs"
[dependencies]
anyhow = "1.0"
byteorder = "1.5"
lzma-rs = "0.3"
wgpu = { version = "25", default-features = false, features = ["dx12", "gles", "vulkan", "wgsl"] }
bytemuck = { version = "1.24", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.18"
md5 = "0.7"
pollster = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zip = { version = "2.2", default-features = false, features = ["deflate"] }
regex-lite = "0.1"
image = { version = "0.25", default-features = false, features = ["bmp", "gif", "ico", "jpeg", "png", "pnm", "qoi", "tga", "tiff", "webp"] }
ab_glyph = "0.2"
bitflags = "2.10"
rosu-pp = "3.1"
hound = "3.5"
woff2-patched = "0.4"
